version: '3'

services:
    redis:
        image: redis
    database:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=KaikkiOnHeikunKeikun
            - POSTGRES_USER=kontti
    backend:
        image: backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=kontti
            - DB_PASSWORD=KaikkiOnHeikunKeikun
            - DB_HOST=database
        restart: unless-stopped
    frontend:
        image: frontend
        ports:
            - 5000:5000

